=== ignitialio/reflib/public/data/schemas/schema.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://json-schema.org/draft-07/schema#",
  "title": "Core schema meta-schema",
  "type": "object",
  "description": "Object",
  "properties": {
    "$id": {
      "type": "string",
      "format": "uri-reference"
    },
    "$schema": {
      "type": "string",
      "format": "uri"
    },
    "$ref": {
      "type": "string",
      "format": "uri-reference"
    },
    "$comment": {
      "type": "string"
    },
    "title": {
      "type": "string",
      "description": "Class title"
    },
    "description": {
      "type": "string",
      "description": "Object description",
      "meta": {
        "textarea": true
      }
    },
    "default": true,
    "readOnly": {
      "type": "boolean",
      "description": "Read only property",
      "default": false
    },
    "examples": {
      "type": "array",
      "items": true
    },
    "multipleOf": {
      "type": "number",
      "exclusiveMinimum": 0
    },
    "maximum": {
      "type": "number",
      "description": "Number max value"
    },
    "exclusiveMaximum": {
      "type": "number"
    },
    "minimum": {
      "type": "number",
      "description": "Number min value"
    },
    "exclusiveMinimum": {
      "type": "number"
    },
    "maxLength": {
      "description": "String max length",
      "type": "integer",
      "minimum": 0
    },
    "minLength": {
      "description": "String min length",
      "allOf": [
        {
          "description": "Non negative integer",
          "type": "integer",
          "minimum": 0
        },
        {
          "default": 0
        }
      ]
    },
    "pattern": {
      "type": "string",
      "description": "Pattern constraint",
      "format": "regex"
    },
    "additionalItems": {
      "description": "Array additional items constraint",
      "$ref": "#"
    },
    "items": {
      "description": "Array items",
      "anyOf": [
        { "$ref": "#" },
        {
          "type": "array",
          "minItems": 1,
          "items": { "$ref": "#" }
        }
      ],
      "default": true
    },
    "maxItems": {
      "description": "Array max number of items",
      "type": "integer",
      "minimum": 0
    },
    "minItems": {
      "description": "Array min number of items",
      "allOf": [
        {
          "description": "Non negative integer",
          "type": "integer",
          "minimum": 0
        },
        {
          "default": 0
        }
      ]
    },
    "uniqueItems": {
      "description": "Array unique items constraint",
      "type": "boolean",
      "default": false
    },
    "contains": { "$ref": "#" },
    "maxProperties": {
      "description": "Maximum number of properties",
      "type": "integer",
      "minimum": 0
    },
    "minProperties": {
      "description": "Minimum number of properties",
      "type": "integer",
      "minimum": 0
    },
    "required": {
      "type": "array",
      "description": "Required fields",
      "items": { "type": "string" },
      "uniqueItems": true,
      "default": []
    },
    "additionalProperties": {
      "description": "Additional properties type constraint",
      "$ref": "#"
    },
    "definitions": {
      "type": "object",
      "additionalProperties": {
        "description": "Additional properties type constraint",
        "$ref": "#"
      },
      "default": {}
    },
    "properties": {
      "type": "object",
      "description": "Properties",
      "additionalProperties": {
        "description": "Additional properties type constraint",
        "$ref": "#"
      },
      "default": {}
    },
    "patternProperties": {
      "type": "object",
      "additionalProperties": {
        "description": "Additional properties type constraint",
        "$ref": "#"
      },
      "propertyNames": { "format": "regex" },
      "default": {}
    },
    "dependencies": {
      "type": "object",
      "additionalProperties": {
        "description": "Additional properties type constraint",
        "anyOf": [
          { "$ref": "#" },
          {
            "type": "array",
            "items": { "type": "string" },
            "uniqueItems": true,
            "default": []
          }
        ]
      }
    },
    "propertyNames": { "$ref": "#" },
    "const": true,
    "enum": {
      "type": "array",
      "description": "Enumeration",
      "items": true,
      "minItems": 1,
      "uniqueItems": true
    },
    "type": {
      "description": "Type",
      "anyOf": [
        {
          "type": "string",
          "description": "Type",
          "enum": [
            "array",
            "boolean",
            "integer",
            "null",
            "number",
            "object",
            "string"
          ]
        },
        {
          "type": "array",
          "description": "Types array",
          "items": {
            "type": "string",
            "enum": [
              "array",
              "boolean",
              "integer",
              "null",
              "number",
              "object",
              "string"
            ]
          },
          "minItems": 1,
          "uniqueItems": true
        }
      ]
    },
    "format": {
      "description": "Type format",
      "type": "string"
    },
    "contentMediaType": { "type": "string" },
    "contentEncoding": { "type": "string" },
    "if": {"$ref": "#"},
    "then": {"$ref": "#"},
    "else": {"$ref": "#"},
    "allOf": {
      "type": "array",
      "minItems": 1,
      "items": { "$ref": "#" }
    },
    "anyOf": {
      "type": "array",
      "minItems": 1,
      "items": { "$ref": "#" }
    },
    "oneOf": {
      "type": "array",
      "minItems": 1,
      "items": { "$ref": "#" }
    },
    "not": { "$ref": "#" }
  },
  "default": true
}

=== ignitialio/reflib/public/data/schemas/notification.schema.json
{
  "title": "Notification",
  "type": "object",
  "description": "User notification",
  "properties": {
    "message": {
      "type": "string",
      "description": "Associated message"
    },
    "user": {
      "type": "string",
      "description": "Destination user"
    },
    "status": {
      "type": "string",
      "enum": [
        "noack",
        "ack"
      ]
    },
    "level": {
      "type": "string",
      "enum": [
        "spam",
        "info",
        "warn",
        "alert",
        "critical"
      ]
    },
    "link": {
      "type": "string",
      "description": "Target URL"
    },
    "image": {
      "type": "string",
      "description": "Image URL"
    }
  }
}
